name: empresa_server
description: Servidor REST da serigrafia (controle de produção)
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  sqlite3: ^2.4.0
  uuid: ^4.4.0

dev_dependencies:
  lints: ^4.0.0
